#!/bin/sh
#
# pepper      This shell script takes care of starting and stopping
#             pepper.
#
# TODO: forwarding only in start
IPV4_FORWARD=/proc/sys/net/ipv4/ip_forward
PEPPER_BIN=/usr/sbin/pepper
PEPPER_CONF=/etc/pepper.conf

if [ ! -f $PEPPER_BIN ]; then 
echo "$PEPPER_BIN not found, exiting.."
exit 0
fi

if [ ! -f $PEPPER_CONF ]; then
echo "$PEPPER_CONF not found, exiting.."
exit 0
fi

case "$1" in
  start)
        echo "Starting pepperspot..."
	# Enable routing of packets: WARNING!!!
	# Users should enable this explicitly
	# echo 1 > /proc/sys/net/ipv4/ip_forward
        echo 1 > $IPV4_FORWARD
        /etc/pepper.iptables
        /etc/pepper.ip6tables
	$PEPPER_BIN &> /dev/null &
	return $?
        ;;
  stop)
        echo "Stopping pepperspot..."
        echo 0 > $IPV4_FORWARD
	iptables -F
	ip6tables -F
	kill -15 `cat /var/run/pepper.pid`
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
